### ISSUE TITLE
damageCauserName: WeapJuliesKar98k_C

### ISSUE THREAD

**Issue by hootyjeremy** [pubg/api-assets#154]
I don't know how to update or do pull requests or if I even have the right but can you add 

`"WeapJuliesKar98k_C": "Kar98k"`

to the dictionaries/telemetry/damageCauserName.json? I found it in one of my games recently. Not entirely sure what it is.

**Comment by thedarkman** [comment]
Actually, as those are the three new weapons, there could be added a few more:
`"WeapDuncansHK416_C": "M416 (Duncan's)"`
`"WeapJuliesKar98k_C": "Kar98k (Julie's)"`
`"WeapMadsQBU88_C": "QBU88 (MAD's)"`

Where as i only guessed the MAD's version based on the others. But i also don't know how to push it myself. I could fix another issue otherwise

**Comment by hootyjeremy** [comment]
Yeah, I've found all three of those in the wild myself and just updated my own dictionary.

Thanks.
