### ISSUE TITLE
why no Steam ID in players API?

### ISSUE THREAD

**Issue by capcaicah** [pubg/api-assets#7]
why in https://api.playbattlegrounds.com/shards/{pc-region} dont give steam id? i think steam id data very important to developer. trims

**Comment by jaloisi834** [comment]
Unfortunately, we are not currently planning to expose personally identifiable information such as steam ID in the API due to security concerns. We will notify everyone if this changes.

NOTE: Going forward, we ask that you only submit assets related issues here. Please help us to keep issues in one place by submitting API requests and bug reports using the "report an api bug" widget on the developer portal (https://developer.playbattlegrounds.com/).
